version: '3.8'
services:
  db:
    container_name: postgres_container
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "Jaime2030"
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - postgres


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8989:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  db-data:
  pgadmin-data: